from django.conf.urls.defaults import *
from django.views.decorators.cache import never_cache
from django.conf import settings

import views
import models
import constants as c
import settings as _settings

urlpatterns = patterns('',
                       
    url(r'^'+settings.IM_URL_PREFIX+'c/(?P<context_slug>[^/]+)(?P<rest>/.*)$',
        views.filter_context,
        name='filter_context'),
    url(r'^'+settings.IM_URL_PREFIX+'c/$',
        views.ContextsView.as_view(),
        name='contexts'),
                       
    url(r'^'+settings.IM_URL_PREFIX+'person/$',
        views.PersonListView.as_view(),
        name='person_list'),
    url(r'^'+settings.IM_URL_PREFIX+'issue/$',
        views.IssueListView.as_view(),
        name='issue_list'),
    url(r'^'+settings.IM_URL_PREFIX+'election/$',
        views.ElectionListView.as_view(),
        name='election_list'),
    url(r'^'+settings.IM_URL_PREFIX+'rationale/$',
        views.RationaleListView.as_view(),
        name='rationale_list'),
    url(r'^'+settings.IM_URL_PREFIX+'rationale/create/?$',
        views.RationaleEditView.as_view(),
        name='rationale_create'),
    url(r'^'+settings.IM_URL_PREFIX+'rationale/(?P<rationale_id>[0-9]+)/?$',
        views.RationaleEditView.as_view(),
        name='rationale_edit'),
    url(r'^'+settings.IM_URL_PREFIX+'election/(?P<slug>[^/]+)/?$$',
        views.PersonListView.as_view(),
        name='election'),
    url(r'^'+settings.IM_URL_PREFIX+'link/$',
        views.LinkListView.as_view(),
        name='link_list'),
    url(r'^'+settings.IM_URL_PREFIX+'link/(?P<url_id>[0-9]+)/$',
        views.LinkListView.as_view(),
        name='link'),
    
    #url(r'^'+settings.IM_URL_PREFIX+'(?P<noun>issue)/submit/$',
    url(r'^'+settings.IM_URL_PREFIX+'issue/submit/$',
        views.SubmitIssueView.as_view(),
        name='issue_submit',
        kwargs=dict(noun='issue')),
    url(r'^'+settings.IM_URL_PREFIX+'issue/submit/search/$',
        views.SubmitIssueView.as_view(),
        name='issue_submit_search',
        kwargs=dict(noun='issue', search=True)),
    url(r'^'+settings.IM_URL_PREFIX+'issue/search/$',
        views.SubmitIssueView.as_view(),
        name='issue_search',
        kwargs=dict(noun='issue', search=True, generic=True, show_no_results=True)),
    url(r'^'+settings.IM_URL_PREFIX+'link/submit/$',
        views.SubmitLinkView.as_view(),
        name='link_submit',
        kwargs=dict(noun='link')),
    url(r'^'+settings.IM_URL_PREFIX+'person/submit/$',
        views.SubmitPersonView.as_view(),
        name='person_submit',
        kwargs=dict(noun='person')),
    url(r'^'+settings.IM_URL_PREFIX+'person/submit/search/$',
        views.SubmitPersonView.as_view(),
        name='person_submit_search',
        kwargs=dict(noun='person', search=True)),
    url(r'^'+settings.IM_URL_PREFIX+'person/search/$',
        views.SubmitPersonView.as_view(),
        name='person_search',
        kwargs=dict(noun='person', search=True, generic=True)),
    
    url(r'^'+settings.IM_URL_PREFIX+'(?P<object_type>issue)/(?P<object_id>[0-9]+)/flag/$',
        'issue_mapper.views.flag',
        name='flag'),
    url(r'^'+settings.IM_URL_PREFIX+'(?P<object_type>link)/(?P<object_id>[0-9]+)/flag/$',
        'issue_mapper.views.flag',
        name='flag'),
    url(r'^'+settings.IM_URL_PREFIX+'(?P<object_type>person)/(?P<object_id>[0-9]+)/flag/$',
        'issue_mapper.views.flag',
        name='flag'),
    url(r'^'+settings.IM_URL_PREFIX+'(?P<object_type>issue)/(?P<object_id>[0-9]+)/flag/confirmed/$',
        'issue_mapper.views.flag',
        {'confirmed':True},
        name='flag_confirmed'),
    url(r'^'+settings.IM_URL_PREFIX+'(?P<object_type>link)/(?P<object_id>[0-9]+)/flag/confirmed/$',
        'issue_mapper.views.flag',
        {'confirmed':True},
        name='flag_confirmed'),
    url(r'^'+settings.IM_URL_PREFIX+'(?P<object_type>person)/(?P<object_id>[0-9]+)/flag/confirmed/$',
        'issue_mapper.views.flag',
        {'confirmed':True},
        name='flag_confirmed'),
    
    url(r'^'+settings.IM_URL_PREFIX+'issue/search/$',
        views.issue_search_ajax,
        name='issue_search_ajax'),
                       
    url(r'^'+settings.IM_URL_PREFIX+'login-register/$',
        views.login_register,
        name='login_register'),
    
    url(r'^'+settings.IM_URL_PREFIX+'issue/(?P<issue_id>[a-z0-9\-]+)/skip/$',
        never_cache(views.skip_issue),
        name='skip_issue'),
    url(r'^'+settings.IM_URL_PREFIX+'issue/(?P<issue_id>[a-z0-9\-]+)/$',
        never_cache(views.IssueView.as_view()),
        name='issue'),
    url(r'^'+settings.IM_URL_PREFIX+'issue/(?P<person_slug>[a-z0-9\-]+)/(?P<issue_id>[a-z0-9\-]+)/$',
        never_cache(views.IssueView.as_view()),
        name='issue_wrt_person'),
    url(r'^'+settings.IM_URL_PREFIX+'issue/(?P<person_slug>[a-z0-9\-]+)/(?P<issue_id>[a-z0-9\-]+)/skip/$',
        never_cache(views.skip_issue),
        name='skip_person_issue'),
    
    url(r'^'+settings.IM_URL_PREFIX+'person/(?P<person_slug>[a-z0-9\.\-]+)(?:/(?P<type>issue))?/$',
        #views.PersonView.as_view(),
        views.IssueListViewSimple.as_view(),
        name='person'),
    url(r'^'+settings.IM_URL_PREFIX+'person/(?P<person_slug>[a-z0-9\.\-]+)/(?P<type>link)/$',
        views.LinkListViewSimple.as_view(),
        name='person'),
    url(r'^'+settings.IM_URL_PREFIX+'person/(?P<person_slug>[a-z0-9\.\-]+)/(?P<type>comment)/$',
        views.CommentListViewSimple.as_view(),
        name='person'),
    url(r'^'+settings.IM_URL_PREFIX+'person/(?P<person_slug>[a-z0-9\.\-]+)/link/(?P<link_slug>[a-z0-9]+)/$',
        #views.PersonView.as_view(),
        views.LinkView.as_view(),
        name='person_link'),
                       
    url(r'^'+settings.IM_URL_PREFIX+'issue/(?P<issue_id>[a-z0-9\-]+)/link/(?P<link_slug>[a-z0-9]+)/$',
        #views.PersonView.as_view(),
        views.LinkView.as_view(),
        name='issue_link'),
                       
    url(r'^'+settings.IM_URL_PREFIX+'issue/(?P<issue_id>[a-z0-9\-]+)/export/csv/$',
        'issue_mapper.views.issue_export_csv',
        name='issue_export_csv'),
    url(r'^'+settings.IM_URL_PREFIX+'issue/(?P<issue_id>[a-z0-9\-]+)/links/older/$',
        'issue_mapper.views.issue_links_older_ajax',
        name='issue_links_older_ajax'),
    
    url(r'^'+settings.IM_URL_PREFIX+'link/(?P<object_id>[0-9]+)/vote/(?P<vote_type>[a-z\-]+)/$',
        'issue_mapper.views.process_vote',
        name='process_link_vote',
        kwargs=dict(object_type=c.LINK)),
    
    url(r'^'+settings.IM_URL_PREFIX+'(?P<object_type>url|urlcontext|link|comment)/(?P<object_id>[0-9]+)/vote/(?P<vote_type>[a-z\-]+)/$',
        'issue_mapper.views.process_vote',
        name='process_vote'),
                       
    url(r'^'+settings.IM_URL_PREFIX+'link/add/$',
        'issue_mapper.views.link_add_ajax',
        name='link_add_ajax'),
    url(r'^'+settings.IM_URL_PREFIX+'link/cross/$',
        'issue_mapper.views.link_cross_ajax',
        name='link_cross_ajax'),
    url(r'^'+settings.IM_URL_PREFIX+'quote/add/$',
        'issue_mapper.views.quote_add_ajax',
        name='quote_add_ajax'),
    url(r'^'+settings.IM_URL_PREFIX+'url/(?P<url_id>[0-9]+)/quotes/$',
        'issue_mapper.views.quote_get_ajax',
        name='quote_get_ajax'),

    url(r'^'+settings.IM_URL_PREFIX+'user/(?P<username>[^/]+)/$',
        views.ProfileView.as_view(),
        name='profile'),

    url(r'^'+settings.IM_URL_PREFIX+'comment/(?P<comment_id>[0-9]+)/$',
        'issue_mapper.views.comment_permalink',
        name='comment_permalink'),
                       
    url(r'^'+settings.IM_URL_PREFIX+'popup/(?P<name>[^/]+)(?:/(?P<type>[^/]+))?(?:/(?P<id>[^/]+))?/$',
        'issue_mapper.views.popup_ajax',
        name='popup_ajax'),
                       
    url(r'^'+settings.IM_URL_PREFIX+'position/set/$',
        'issue_mapper.views.position_set_ajax',
        name='position_set_ajax'),

    url(r'^'+settings.IM_URL_PREFIX+'motion/$',
        views.MotionListView.as_view(),
        name='motion_list'),
                       
    url(r'^'+settings.IM_URL_PREFIX+'motion/(?P<motion_id>[0-9]+)/$',
        views.MotionView.as_view(),
        name='motion'),
                       
    url(r'^'+settings.IM_URL_PREFIX+'motion/(?P<object_type>[a-z0-9\-]+)/(?P<object_id>[a-z0-9\-]+)/(?P<attribute>[a-zA-Z0-9\-_]+)/(?P<vote_type>[a-z]+)/$',
        'issue_mapper.views.motion_ajax',
        name='motion_ajax'),
                       
    url(r'^'+settings.IM_URL_PREFIX+'comment/create/(?P<object_type>[a-z0-9\-]+)/(?P<object_id>[a-z0-9\-]+)/$',
        'issue_mapper.views.comment_create_ajax',
        name='comment_create_ajax'),
                       
    url(r'^'+settings.IM_URL_PREFIX+'comment/delete/(?P<comment_id>[a-z0-9\-]+)/$',
        'issue_mapper.views.comment_delete_ajax',
        name='comment_delete_ajax'),
                       
    url(r'^'+settings.IM_URL_PREFIX+'search/(?P<type>[^/]+)(?:/(?P<term>[^/]+))?/$',
        'issue_mapper.views.search_ajax',
        name='search_ajax'),
    
    url(r'^'+settings.IM_URL_PREFIX+'u/(?P<username>[^/]+)/privileges/$',
        views.UserPrivilegeView.as_view(),
        name='user_privilege'),
                       
    url(r'^test/(?P<name>[^/]+)/', views.test),
    #url(r'^logout/(?P<next_page>.*)/$', 'django.contrib.auth.views.logout', name='auth_logout_next')
)
